name: Build Windows Executable

on:
  push:
    branches:
      - main  # Spustí sa pri každom pushnutí do hlavnej vetvy

jobs:
  build:
    runs-on: windows-latest  # Spustenie na Windows serveri

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Stiahne kód z tvojho repozitára

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8  # Použijeme Python 3.8 pre kompatibilitu s Windows 7/8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Create photos directory
        run: mkdir photos  # Automaticky vytvorí priečinok photos

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole --win-private-assemblies --icon=logo.png main.py
        shell: cmd

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: evidencia-osob-exe
          path: dist/main.exe  # Nahraj .exe ako artefakt
