name: Build Windows Executable

on:
  push:
    branches:
      - main  # Workflow sa spustí po pushnutí do hlavnej vetvy

jobs:
  build:
    runs-on: windows-latest  # Workflow beží na Windows serveri

    steps:
      # 1. Stiahnutie kódu z repozitára
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Nastavenie Pythonu 3.8 (kompatibilita pre Windows 7/8)
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      # 3. Inštalácia závislostí vrátane PyInstaller
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      # 4. Vytvorenie priečinka na fotografie
      - name: Create photos directory
        run: mkdir photos

      # 5. Zostavenie .exe súboru pomocou PyInstaller
      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole --icon=logo.png main.py
        shell: cmd  # Použitie Windows CMD

      # 6. Nahratie výsledného .exe súboru ako artefakt
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: evidencia-osob-exe
          path: dist/main.exe
