name: Build Windows Executable

on:
  push:
    branches:
      - main  # Spustí sa, keď pushneš zmeny do hlavnej vetvy

jobs:
  build:
    runs-on: windows-latest  # Spustenie na Windows serveri

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Stiahne tvoj kód

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8  # Použitie kompatibilnej verzie Pythonu

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller pillow  # Nainštaluje závislosti

      - name: Create photos directory
        run: mkdir photos  # Vytvorí priečinok photos, ak neexistuje

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --win-private-assemblies --icon=logo.png main.py
        shell: cmd  # Príkazový shell pre správnu kompatibilitu

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: evidencia-osob-exe
          path: dist/main.exe  # Nahraj .exe súbor ako artefakt
